### ISSUE TITLE
Log gamma output noise prior

### ISSUE THREAD

**Issue by deepakdalakoti** [cics-nd/rans-uncertainty#1]
Hi,

I was looking at the code for the log of the gamma output noise prior as computed in the compute_loss function in foamSVGD.py. Currently the code reads,

```
prior_log_beta = (self.prior_beta_shape * self.models[index].log_beta \
                        - self.models[index].log_beta.exp() * self.prior_beta_rate).sum()

```

I believe the correct form should be

```
prior_log_beta = ((self.prior_beta_shape-1.0) * self.models[index].log_beta \
                        - self.models[index].log_beta.exp() * self.prior_beta_rate).sum()

```

Is this correct or am I missing something?

Regards

**Comment by NickGeneva** [comment]
You seem to be correct. Appears this bug existed in our original SVGD implementation. I will correct that repository as well.

Thanks for reporting it!

**Comment by thw1021** [comment]
@NickGeneva @deepakdalakoti 
Could you explain why `self.prior_beta_shape` should minus `1`, please ?

**Comment by NickGeneva** [comment]
The prior on the beta term is a [Gamma distribution](https://en.wikipedia.org/wiki/Gamma_distribution). 
![Gamma PDF](https://wikimedia.org/api/rest_v1/media/math/render/svg/3373bd46a7261833556cec0a5c95f51ab4b0e74d)

Taking the log of the Gamma distribution and only keeping the terms with beta in them results in (shape-1)* log(beta) + (- beta*rate).
