### ISSUE TITLE
expectation and variance of beta

### ISSUE THREAD

**Issue by hwfluid** [cics-nd/rans-uncertainty#16]
@NickGeneva 
I have a small question about the expectation and variance of beta. It is Gamma distributed with `shape=100`, `rate=2e-4`.

In the paper, you wrote "This weakly promotes large beta with an expected value of 5e5 and a variance on the order of 1e-3". However, based on the equation [here](https://en.wikipedia.org/wiki/Gamma_distribution), the expectation should be `shape / rate = 5e5`, and the variance should be `shape / (rate * rate) = 2.5e9`. Do I misunderstand something ?

**Comment by NickGeneva** [comment]
Yes, you are correct. The variance should be very large (not small) as this results in the prior being weak during the optimization process! Generally the variance for the noise (epsilon) with only increase during the optimization process (so beta will decrease iirc)

I cannot remember what I was referring to in the paper... perhaps I was referring the variance of the Gaussian (but this wouldn't be correct) or maybe the beta distribution. Also don't remember if I was refer before or after optimization. Regardless this is really ambiguous on my part.

 So I would regard this as a typo in the paper.  You are spot on with the beta variance. Apologies for the confusion.
