### ISSUE TITLE
Cannot convert mesh from .geo to .msh

### ISSUE THREAD

**Issue by aiskhak** [cics-nd/rans-uncertainty#6]
Cannot convert mesh from .geo to .msh. The problem is that it is necessary to specify
-format msh2 
in meshes/convert-mesh.sh

./gmsh ${MESH_NAME}.geo -3 -o ${MESH_NAME}.msh -algo frontal -algo front3d -format msh2

**Comment by NickGeneva** [comment]
Thank you for the bug fix. New GMSH format seems to cause the conversion program some head aches. Fixed and documented.
