### ISSUE TITLE
There is no .geo mesh for square-cylinder case

### ISSUE THREAD

**Issue by aiskhak** [cics-nd/rans-uncertainty#7]
There is no .geo mesh for square-cylinder case for RANS and LES.
Could you please upload them?

Regards,
Arsen

**Comment by NickGeneva** [comment]
There is no gmsh mesh for the square cylinder case, I used OpenFOAM internal meshing tools to make this mesh. Familiarize yourself with the OpenFOAM meshing utility and the file:

[https://github.com/cics-nd/rans-uncertainty/blob/master/training-data/square-cylinder/openfoam/system/blockMeshDict](https://github.com/cics-nd/rans-uncertainty/blob/master/training-data/square-cylinder/openfoam/system/blockMeshDict)
